// Autogenerated, do not edit. All changes will be undone.
// Fri Apr 06 2018 11:15:44 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Thu Apr 05 2018 06:11:07 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Fri Mar 30 2018 06:34:50 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Thu Mar 29 2018 13:13:07 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Thu Mar 29 2018 13:06:16 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Thu Mar 29 2018 12:18:07 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Sun Mar 25 2018 16:46:26 GMT+0200 (CEST)
// Autogenerated, do not edit. All changes will be undone.
// Sun Mar 25 2018 00:29:25 GMT+0100 (CET)
// Autogenerated, do not edit. All changes will be undone.
// Fri Mar 23 2018 18:45:39 GMT+0100 (CET)
// Autogenerated, do not edit. All changes will be undone.
// Thu Mar 22 2018 17:40:10 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Thu Mar 22 2018 17:23:33 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Thu Mar 22 2018 17:21:59 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Thu Mar 22 2018 17:16:58 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Thu Mar 22 2018 17:15:08 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Thu Mar 22 2018 10:33:32 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Wed Mar 21 2018 12:44:20 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Wed Mar 21 2018 07:20:29 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Tue Mar 20 2018 19:18:46 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Mon Mar 19 2018 13:39:32 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Mon Mar 19 2018 12:29:18 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Mon Mar 19 2018 12:26:18 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Fri Mar 16 2018 17:49:36 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Fri Mar 16 2018 17:46:05 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Fri Mar 16 2018 17:37:25 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Thu Mar 15 2018 08:45:52 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Thu Mar 15 2018 06:25:29 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Thu Mar 15 2018 04:56:17 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Wed Mar 14 2018 15:26:03 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Wed Mar 14 2018 08:52:07 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Tue Mar 13 2018 16:13:12 GMT-0400 (EDT)
// Autogenerated, do not edit. All changes will be undone.
// Fri Mar 09 2018 06:05:32 GMT-0500 (EST)
// Autogenerated, do not edit. All changes will be undone.
// Thu Mar 08 2018 10:02:44 GMT-0500 (EST)
// Autogenerated, do not edit. All changes will be undone.
// Wed Mar 07 2018 17:14:26 GMT-0500 (EST)
// Autogenerated, do not edit. All changes will be undone.
// Wed Mar 07 2018 10:28:27 GMT-0500 (EST)
// Autogenerated, do not edit. All changes will be undone.
// Wed Mar 07 2018 09:02:49 GMT-0500 (EST)
// Autogenerated, do not edit. All changes will be undone.
// Tue Mar 06 2018 17:47:54 GMT-0500 (EST)
// Autogenerated, do not edit. All changes will be undone.
// Mon Mar 05 2018 09:23:37 GMT-0500 (EST)
// Autogenerated, do not edit. All changes will be undone.
// Mon Mar 05 2018 09:18:09 GMT-0500 (EST)
// Autogenerated, do not edit. All changes will be undone.
// Fri Mar 02 2018 14:28:12 GMT-0500 (EST)
// Autogenerated, do not edit. All changes will be undone.
// Fri Mar 02 2018 10:07:59 GMT-0500 (EST)
// Autogenerated, do not edit. All changes will be undone.
// Fri Mar 02 2018 10:07:07 GMT-0500 (EST)
/* MAIN JS
--------------------------------------------*/

(function($) {

  // BASE SETUP ------------------------------------//

  // Add js class to html element.
  document.documentElement.className += ' js';

  // Add class for IE10.
  if (Function('/*@cc_on return document.documentMode===10@*/')()) {
    document.documentElement.className += ' ie10';
  }

  // Lazy load images.
  if ($('img.lazy').length) {
    $('img.lazy').show().lazyload({
      threshold: 100,
      failure_limit: 9999,
    });
  }

  // Check window width
  var getWidth = function() {
    var width;
    if (document.body && document.body.offsetWidth) {
      width = document.body.offsetWidth;
    }
    if (document.compatMode === 'CSS1Compat' &&
      document.documentElement &&
      document.documentElement.offsetWidth) {
      width = document.documentElement.offsetWidth;
    }
    if (window.innerWidth) {
      width = window.innerWidth;
    }
    return width;
  };
  window.onload = function() {
    getWidth();
  }
  window.onresize = function() {
    getWidth();
  }

  // SITE SPECIFIC JS ------------------------------//

  var toggleClasses = function(element) {
    var $this = element,
        $togglePrefix = $this.data('prefix') || 'this';

    // If the element you need toggled is relative to the toggle, add the
    // .js-this class to the parent element and "this" to the data-toggled attr.
    if ($this.data('toggled') == "this") {
      var $toggled = $this.parents('.js-this');
    } else {
      var $toggled = $('.' + $this.data('toggled'));
    }

    $this.toggleClass($togglePrefix + '-is-active');
    $toggled.toggleClass($togglePrefix + '-is-active');

    // Remove a class on another element, if needed.
    if ($this.data('remove')) {
      $('.' + $this.data('remove')).removeClass($this.data(
            'remove'));
    }

  };

  /*
   * Toggle Active Classes
   *
   * @description:
   *  toggle specific classes based on data-attr of clicked element
   *
   * @requires:
   *  'js-toggle' class and a data-attr with the element to be
   *  toggled's class name both applied to the clicked element
   *
   * @example usage:
   *  <span class="js-toggle" data-toggled="toggled-class">Toggler</span>
   *  <div class="toggled-class">This element's class will be toggled</div>
   *
   */
  $('.js-toggle').on('click', function(e) {
    e.stopPropagation();
    toggleClasses($(this));
  });

  // Toggle parent class
  $('.js-toggle-parent').on('click', function(e) {
    e.preventDefault();
    var $this = $(this);
    $this.toggleClass('is-active');
    $this.parent().toggleClass('is-active');
  });

  // Toggle hovered classes
  $('.js-hover').on('mouseenter mouseleave', function(e) {
    e.preventDefault();
    toggleClasses($(this));
  });

  // Slick carousel (single item)
  if ($('.js-carousel__single-item').length) {
    $('.js-carousel__single-item').slick({
      lazyLoad: 'ondemand',
      speed: 300,
      mobileFirst: true,
      autoplay: true,
      autoplaySpeed: 4000,
      cssEase: 'ease-out',
      fade: true,
      nextArrow: '.arrow__next',
      prevArrow: '.arrow__prev',
      touchThreshold: 11,
      dots: true,
      adaptiveHeight: true
    });
  }

  // Slick carousel (multiple items)
  if ($('.js-carousel__multi-item').length) {
    $('.js-carousel__multi-item').slick({
      speed: 300,
      mobileFirst: true,
      autoplay: true,
      autoplaySpeed: 4000,
      cssEase: 'ease-out',
      nextArrow: '.arrow__next',
      prevArrow: '.arrow__prev',
      touchThreshold: 11,
      dots: false,
      slidesToShow: 1,
      slidesToScroll: 1,
      responsive: [
        {
          breakpoint: 500,
          settings: {
            slidesToShow: 2,
            slidesToScroll: 2
          }
        },
        {
          breakpoint: 700,
          settings: {
            slidesToShow: 3,
            slidesToScroll: 3
          }
        }
      ]
    });
  }

  // Show/ Hide main nav on scroll.
  var orgTop = 80;
  $(window).scroll(function() {
    if (getWidth() < 700) {
      var currentTop = $(this).scrollTop(),
          $navBar = $('.header');

      if (currentTop > orgTop && !$('.header.nav-is-active').length) {
        $navBar.addClass('hide-nav');
      } else {
        $navBar.removeClass('hide-nav');
      }

      // Be sure not to hide it too soon.
      if (currentTop < 80) {
        $navBar.removeClass('hide-nav');
      } else {
        orgTop = currentTop;
      }
    }
  });

  // Responsive videos
  if ($.fn.fitVids) {
    $('.article__body, .text, .fitvid').fitVids();
  }

  // Apply parallax effect to background images.
  function parallaxIt() {
    var $fwindow = $(window),
        scrollTop = window.pageYOffset || document.documentElement.scrollTop;

    // On window scroll event.
    $fwindow.on('scroll resize', function() {
      scrollTop = window.pageYOffset || document.documentElement.scrollTop;
    });

    // Apply parallax effect to inner content (if applicable).
    $('[data-type="content"]').each(function (index, e) {
      var $contentObj = $(this),
          fgOffset = parseInt($contentObj.offset().top),
          yPos,
          speed = ($contentObj.data('speed') || 1 );

      $fwindow.on('scroll resize', function (){
        yPos = fgOffset - scrollTop / speed;
        $contentObj.css('top', yPos);
      });
    });

    // Parallax the background image.
    $('[data-type="background"]').each(function(){
      var $backgroundObj = $(this),
          bgOffset = parseInt($backgroundObj.offset().top),
          yPos,
          coords,
          speed = ($backgroundObj.data('speed') || 0 );

      $fwindow.on('scroll resize', function() {
        yPos = - ((scrollTop - bgOffset) / speed);
        coords = '50% '+ yPos + 'px';
        $backgroundObj.css({ backgroundPosition: coords });
      });
    });

    // Triggers winodw scroll for refresh,
    $fwindow.trigger('scroll');
  };

  // Init parallax
  if ($('.has-parallax').length) {
    parallaxIt()
  }


  // FitText for logo subbrands.
  // $('.js-logo-fit .line1').fitText(.55);
  // $('.js-logo-fit .line2').fitText(.9);
  // $('.js-logo-fit .line3').fitText(.79);


  /**
   * Modaal functionality
   * Reference:
   */
  if ($.fn.modaal) {
    $('.js-modal-image').modaal({
      type: 'image'
    });
  }


  // Theme switcher for primary colors
  $('.theme-swatches--primary .swatch').click(function(){
    var thisColor = $(this).data('color');

    $('.theme-swatches--primary .swatch').removeClass('active');
    $(this).addClass('active');

    // Remove any class that starts with "theme--"
    $('html').removeClass(function(index, css) {
      return (css.match (/(^|\s)theme--\S+/g) || []).join(' ');
    }).addClass('theme--' + thisColor);
  });

  // Theme switcher for secondary colors
  $('.theme-swatches--secondary .swatch').click(function(){
    var thisColor = $(this).data('color');

    $('.theme-swatches--secondary .swatch').removeClass('active');
    $(this).addClass('active');

    // Remove any class that starts with "theme--"
    $('body').removeClass(function(index, css) {
      return (css.match (/(^|\s)theme--\S+/g) || []).join(' ');
    }).addClass('theme--' + thisColor);
  });

  // Theme switcher for dark colors
  $('.theme-swatches--dark .swatch').click(function() {
    $('body').toggleClass('dark');
    $(this).toggleClass('active');
  });

})(jQuery); // Fully reference jQuery after this point.
